server: 
  port: 9015

spring: 
  datasource: 
    url: jdbc:postgresql://joeydb.cpthsxeojuz1.us-east-2.rds.amazonaws.com:5432/project2db
    username: project2user
    password: p4ssw0rd
    driver-class-name: org.postgresql.Driver
  jpa: 
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate: 
      ddl-auto: update
  mail: 
    host: smtp.gmail.com
    port: 587
    username: readme.revature@gmail.com
    password: fusdrelyakfhrokg
    properties: 
      mail: 
        smtp: 
          auth: true
          starttls:
            enable: true